### ISSUE TITLE
Failed to get session id

### ISSUE THREAD

**Issue by jochemstoel** [hissincn/suno-ai#1]
I copied the value of ```document.cookie``` from my devtools on suno.ai and used it in your example script.

The following error occurs:
```
Error: Failed to get session id
    at e.<anonymous> (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:11774)
    at m (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:2797)
    at Generator.<anonymous> (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:4139)
    at Generator.next (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:3226)
    at s (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:8700)
    at r (c:\Users\Jochem\Desktop\sunoai\node_modules\suno-ai\dist\index.js:2:8903)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Error: Failed to get session id
```

What is the problem? Do I need something else than document.cookie, maybe it needs to be processed to JSON or something?

**Comment by hissincn** [comment]
i am fixing this
